"""Task 1 foundation tables

Revision ID: 433d5b173cce
Revises:
Create Date: 2026-10-05 19:59:03.690119
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.models.entities import BaseUnits

# revision identifiers, used by Alembic.
revision: str = "433d5b173cce"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("totp_secret", sa.String(length=64), nullable=True),
        sa.Column("pending_totp_secret", sa.String(length=64), nullable=True),
        sa.Column("last_totp_step", sa.Integer(), nullable=True),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("org_unit", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("role IN ('INVESTIGATOR','SUPERVISOR','ADMIN')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_ref", sa.String(length=40), nullable=False),
        sa.Column("sahyog_ref", sa.String(length=80), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("gang_case_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.CheckConstraint("status IN ('OPEN','TRACING','ATTRIBUTED','FREEZE_PENDING','CLOSED')"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sahyog_ref"),
    )
    op.create_index(op.f("ix_cases_case_ref"), "cases", ["case_ref"], unique=True)
    op.create_index(op.f("ix_cases_created_at"), "cases", ["created_at"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_table(
        "case_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("extracted_json", sa.JSON(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_attachments_case_id"), "case_attachments", ["case_id"], unique=False
    )
    op.create_table(
        "victim_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.String(length=20), nullable=False),
        sa.Column("tx_hash", sa.String(length=66), nullable=True),
        sa.Column("victim_address", sa.String(length=100), nullable=True),
        sa.Column("suspect_address", sa.String(length=100), nullable=True),
        sa.Column("token", sa.String(length=20), nullable=True),
        sa.Column("amount", BaseUnits(), nullable=True),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("tx_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("chain IN ('ethereum','bnb','polygon','tron','bitcoin')"),
        sa.CheckConstraint("status IN ('PENDING_RESOLUTION','REPORTED')"),
        sa.CheckConstraint("decimals IS NULL OR (decimals >= 0 AND decimals <= 30)"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "chain", "tx_hash", name="uq_case_chain_tx"),
    )
    op.create_index(
        op.f("ix_victim_transactions_case_id"), "victim_transactions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_victim_transactions_chain"), "victim_transactions", ["chain"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_victim_transactions_chain"), table_name="victim_transactions")
    op.drop_index(op.f("ix_victim_transactions_case_id"), table_name="victim_transactions")
    op.drop_table("victim_transactions")
    op.drop_index(op.f("ix_case_attachments_case_id"), table_name="case_attachments")
    op.drop_table("case_attachments")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_at"), table_name="cases")
    op.drop_index(op.f("ix_cases_case_ref"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
